name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
template: |
  ## What's Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

  ---

  *This release was automatically created by [Release Drafter](https://github.com/release-drafter/release-drafter).*
